---
kind: pipeline
name: default

steps:
- name: build
  image: docker
  environment:
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
  commands:
  - export DOCKER_HOST=unix:///var/run/host.sock
  - if [[ $DRONE_TAG ]]; then export DOCKER_TAG=$DRONE_TAG; else export DOCKER_TAG=$DRONE_BUILD_NUMBER; fi 
  - docker login -u 'robot$drone' -p $DOCKER_PASSWORD harbor.dsrd.libraries.psu.edu
  - docker build -t harbor.dsrd.libraries.psu.edu/public/php-docker-base:$DOCKER_TAG . 
  - docker tag harbor.dsrd.libraries.psu.edu/public/php-docker-base:$DOCKER_TAG harbor.dsrd.libraries.psu.edu/public/php-docker-base:latest
  - docker push harbor.dsrd.libraries.psu.edu/public/php-docker-base
  when:
    events: [ tags ]
    branches: [ master ]
  volumes:
  - name: docker-sock
    path: /var/run/host.sock

volumes:
- name: docker-sock
  host:
    path: /var/run/docker.sock

